const grupos = 
[
    [
    {
        cod: "5CG1",
        grupo: "5° Científico G.1"
        
    },
    [
        { numeroLista: "01", nombre: 'Juan', apellido: 'Pérez', imagen: 'juan.png' },
        { numeroLista: "02", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "03", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "04", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "05", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "06", nombre: 'María', apellido: 'Gómez', imagen: '../f.png' },
        { numeroLista: "07", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "08", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "09", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "10", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "11", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "12", nombre: 'Martin', apellido: 'Terra', imagen: '../m.png' },
        { numeroLista: "13", nombre: 'Marta de las Carreras', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "14", nombre: 'Marta Noel', apellido: 'Gomensoro', imagen: 'maria.png' },
        { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "16", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "17", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "18", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "19", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "20", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "21", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "22", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "23", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "24", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "25", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "26", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "27", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "28", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' }
    ]],
    [
    {
        cod: "6IG1",
        grupo: "6° Ingenieria G.1"
    },
    [{ numeroLista: "01", nombre: 'Juan', apellido: 'Pérez', imagen: 'juan.png' },
    { numeroLista: "02", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "03", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "04", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "05", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "06", nombre: 'María', apellido: 'Gómez', imagen: '' },
    { numeroLista: "07", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "08", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "09", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "10", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "11", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "12", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "14", nombre: 'María Noel', apellido: 'Gomensoro', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'Marta de las Carrerass', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "16", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' }
    ]],
    [
    {
        cod: "6AG1",
        grupo: "6° Arquitectura G.1"
    },
    [{ numeroLista: "01", nombre: 'Juan', apellido: 'Pérez', imagen: 'juan.png' },
    { numeroLista: "02", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "03", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "04", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "05", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "06", nombre: 'María', apellido: 'Gómez', imagen: '' },
    { numeroLista: "07", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "08", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "09", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "10", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "12", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "12", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "14", nombre: 'María Noel', apellido: 'Gomensoro', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "13", nombre: 'Marta de las Carrerass', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "15", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
    { numeroLista: "16", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' }
    ]],
    [
        {
            cod: "6EG2",
            grupo: "6° Economia G.2"
        },
        [{ numeroLista: "01", nombre: 'Juan', apellido: 'Pérez', imagen: 'juan.png' },
        { numeroLista: "02", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "03", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "04", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: '../f.png' },
        { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "13", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' },
        { numeroLista: "13", nombre: 'Jose', apellido: 'Manrique', imagen: '../m.png' },
        { numeroLista: "16", nombre: 'María', apellido: 'Gómez', imagen: 'maria.png' }
    ]]
]